name = "rss-news-api"
compatibility_date = "2024-09-22"
compatibility_flags = [ "nodejs_compat_v2" ]
main = "src/index.ts"

[vars]
SUPABASE_URL = "https://kufgxlxxxxxxqwdpxo.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIxxxxxxxxxxxxxxxxxxxxxxxxx..."
TELEGRAM_BOT_URL = "https://api.telegram.org/bot7909xxxx462:AAGJTORVxxxxxxxxxxxxxxxxxxx/sendMessage"
CHAT_ID = "-10023296xxxxx"

[triggers]
crons = ["*/1 * * * *"] 

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"